{% set name = "indicators" %}
{% set version = "2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/p-ranav/indicators/archive/v{{ version }}.tar.gz
  sha256: 37e60a6b27460b0ade086a8515ad920919ffc43ed8935af1aaa95c48e3284c34

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -d ${PREFIX}/include/indicators  # [unix]
    - test -f ${PREFIX}/include/indicators/progress_bar.hpp  # [unix]
    - if exist %LIBRARY_PREFIX%\include\indicators\progress_bar.hpp (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/p-ranav/indicators
  license: MIT
  license_file: LICENSE
  summary: Indicators is a header-only library that introduces highly personalizible progress bars.

extra:
  recipe-maintainers:
    - p-ranav
    - SylvainCorlay
    - wolfv
    - marimeireles
